CREATE TABLE [dbo].[PROJ_TASK] (
    [PROJECTID]                    FLOAT (53)     NOT NULL,
    [TASKUNIQUEID]                 FLOAT (53)     NOT NULL,
    [TASKID]                       FLOAT (53)     NULL,
    [TASK_STATUS]                  FLOAT (53)     NULL,
    [CONTACT]                      VARCHAR (255)  NULL,
    [CRITICAL]                     FLOAT (53)     NULL,
    [TASK_TYPE]                    FLOAT (53)     NULL,
    [EXPECTED_START_DATE]          DATETIME       NULL,
    [EXPECTED_END_DATE]            DATETIME       NULL,
    [EARLIEST_START_DATE]          DATETIME       NULL,
    [NEXT_CRITICAL_TASK_ID]        FLOAT (53)     NULL,
    [PREVIOUS_CRITICAL_TASK_ID]    FLOAT (53)     NULL,
    [BM_SCHED_START_DATE]          DATETIME       NULL,
    [BM_SCHED_END_DATE]            DATETIME       NULL,
    [MILESTONE_DATE]               DATETIME       NULL,
    [PROJECTNAME]                  VARCHAR (255)  NULL,
    [LAST_DURATION_UPDATE_DATE]    DATETIME       NULL,
    [CONTRACTUAL_MS]               FLOAT (53)     NULL,
    [CCCB_TASK_FED]                FLOAT (53)     NULL,
    [CMSB_TASK_FED]                FLOAT (53)     NULL,
    [CCFB_TASK_FED]                FLOAT (53)     NULL,
    [CCCB_PENETRATION]             FLOAT (53)     NULL,
    [CMSB_PENETRATION]             FLOAT (53)     NULL,
    [CCFB_PENETRATION]             FLOAT (53)     NULL,
    [MAX_EATING_ACTIVITY]          FLOAT (53)     NULL,
    [MAX_EATING_ACTIVITY_NAME]     VARCHAR (1024) NULL,
    [MAX_EATING_ACTIVITY_MANAGER]  VARCHAR (255)  NULL,
    [CRITICAL_TASK_FED]            FLOAT (53)     NULL,
    [CRITICAL_TASK_FED_NAME]       VARCHAR (1024) NULL,
    [TEXT_18]                      VARCHAR (255)  NULL,
    [TEXT_19]                      VARCHAR (255)  NULL,
    [TEXT_20]                      VARCHAR (255)  NULL,
    [TEXT_22]                      VARCHAR (255)  NULL,
    [TEXT_26]                      VARCHAR (255)  NULL,
    [TEXT_27]                      VARCHAR (255)  NULL,
    [TEXT_28]                      VARCHAR (255)  NULL,
    [TEXT_29]                      VARCHAR (255)  NULL,
    [TEXT_30]                      VARCHAR (255)  NULL,
    [ORIGINAL_TARGET_DATE]         DATETIME       NULL,
    [DATE_9]                       DATETIME       NULL,
    [DATE_10]                      DATETIME       NULL,
    [NUMBER_4]                     FLOAT (53)     NULL,
    [PRIORITY_LEVEL]               FLOAT (53)     NULL,
    [PRIORITY_LEVEL_PENETRATION]   FLOAT (53)     NULL,
    [COLOR]                        FLOAT (53)     NULL,
    [NAME]                         VARCHAR (1024) NULL,
    [DURATION]                     FLOAT (53)     NULL,
    [REMAININGDURATION]            FLOAT (53)     NULL,
    [PERCENTCOMPLETE]              FLOAT (53)     NULL,
    [ACTUALSTART]                  DATETIME       NULL,
    [ACTUALFINISH]                 DATETIME       NULL,
    [SUMMARY]                      FLOAT (53)     NULL,
    [READYTOSTART]                 FLOAT (53)     NULL,
    [MAX_EATING_ACTIVITY_UNIQUEID] FLOAT (53)     NULL,
    [DURATION1]                    NUMERIC (18)   NULL,
    [LEVELING_PRIORITY]            NUMERIC (18)   NULL,
    [CONSTRAINING_TASK]            NUMERIC (18)   NULL,
    [CONSTRAINT_PRIORITY]          NUMERIC (18)   NULL,
    [DURATION2]                    NUMERIC (18)   NULL,
    [EXPORTED_P2P]                 NUMERIC (18)   NULL,
    [P2P_MILESTONE]                NUMERIC (2)    NULL,
    [MILESTONE]                    NUMERIC (2)    NULL,
    [ACTUALDURATION]               NUMERIC (18)   NULL,
    [UBP_FIXED]                    NUMERIC (6)    NULL,
    [UBP_PERCENT]                  NUMERIC (6)    NULL,
    [P2P_MILESTONE_DATE]           DATETIME       NULL,
    [STARTDATE]                    DATETIME       NULL,
    [FINISHDATE]                   DATETIME       NULL,
    [BASELINESTART]                DATETIME       NULL,
    [BASELINEFINISH]               DATETIME       NULL,
    [SPLIT_DATE]                   DATETIME       NULL,
    [NUMBER_1]                     NUMERIC (18)   NULL,
    [BASE_PRIORITY_LEVEL]          FLOAT (53)     NULL,
    [BASE_PRIORITY_LEVEL_PEN]      FLOAT (53)     NULL,
    [BASE_COLOR]                   FLOAT (53)     NULL,
    [EXPECTED_START_DATE_SUBZERO]  DATETIME       NULL,
    [IMMED_P2P_PRIORITY_PROJECTID] FLOAT (53)     NULL,
    [IMMED_P2P_PRIORITY_TASKUID]   FLOAT (53)     NULL,
    [FINAL_P2P_PRIORITY_PROJECTID] FLOAT (53)     NULL,
    [FINAL_P2P_PRIORITY_TASKUID]   FLOAT (53)     NULL,
    [BASE_PRIORITY_LEVEL_BUFID]    FLOAT (53)     NULL,
    [NUMBER_11]                    FLOAT (53)     NULL,
    [IGNOREVALUESABOVEPERCENT]     NUMERIC (10)   NULL,
    [FLAG1]                        NUMERIC (10)   NULL,
    [NUMBER_9]                     NUMERIC (18)   NULL,
    [ALL_PREDS_CO]                 NUMERIC (10)   NULL,
    [BM_BUFFER_PEN_START_DATE]     DATETIME       NULL,
    [RESOURCES]                    VARCHAR (1024) NULL,
    [TEXT_3]                       VARCHAR (255)  NULL,
    [TEXT_11]                      VARCHAR (255)  NULL,
    [TEXT_12]                      VARCHAR (255)  NULL,
    [TEXT_13]                      VARCHAR (2048) NULL,
    [TEXT_15]                      VARCHAR (2048) NULL,
    [OUTLINE_LEVEL]                NUMERIC (18)   NULL,
    [BUFFER_FED_STRING]            VARCHAR (255)  NULL,
    [BUFFER_PENETRATION_STRING]    VARCHAR (255)  NULL,
    [HASREASONCODE]                NUMERIC (10)   NULL,
    [REASONCODEUID]                NUMERIC (10)   NULL,
    [START_DELAY]                  NUMERIC (18)   NULL,
    [COMPL_DELAY]                  NUMERIC (18)   NULL,
    [NO_ADDL_DELAY_FLAG]           NUMERIC (10)   NULL,
    [NO_ADDL_DELAY_START]          DATETIME       NULL,
    [NO_ADDL_DELAY_COMPL]          DATETIME       NULL,
    [TOTAL_REASON_DELAY]           NUMERIC (10)   NULL,
    [TOTAL_REASON_COUNT]           NUMERIC (10)   NULL,
    [REASON_CREATE_DATE]           DATETIME       NULL,
    [CURR_REASON_NAME]             VARCHAR (128)  NULL,
    [CURR_REASON_COMMENTS]         VARCHAR (255)  NULL,
    [CURR_REASON_CHOICELIST]       VARCHAR (128)  NULL,
    [IS_PARENT_TASK]               NUMERIC (10)   NULL,
    [HAS_CHECKLIST]                NUMERIC (2)    NULL,
    [REASON_PROMPT_FLAG]           NUMERIC (10)   NULL,
    [SPECIALTASKTYPE]              NUMERIC (2)    NULL,
    [NEED_DATE]                    DATETIME       NULL,
    [TOTAL_DAYS_OPEN]              NUMERIC (18)   NULL,
    [UPDATE_BUF_PEN]               NUMERIC (2)    NULL,
    [EXPECTED_START_TODAY]         SMALLINT       NULL,
    [SUBTASK_COUNT]                SMALLINT       NULL,
    CONSTRAINT [PK_PROJ_TASK] PRIMARY KEY CLUSTERED ([PROJECTID] ASC, [TASKUNIQUEID] ASC)
);

